services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chicken_db
    ports:
      - "3306:3306"

  api:
    build: ./01_api
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_NAME: chicken_db
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  frontend:
    build: ./02_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_HOST: http://api:3001
    depends_on:
      - api